name: Payload
on:
  release:
    types:
      - published 
      - unpublished 
      - created 
      - edited 
      - deleted 
      - prereleased
      - released

jobs:
  payload:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
